### ISSUE TITLE
Issue with Elm 0.17?

### ISSUE THREAD

**Issue by domenkozar** [vic/elmx-webpack-preloader#1]
I'm not sure if this is Elm 0.17 issue, but might be:

```
/home/ielectric/dev/hydra-frontend/node_modules/elmx-webpack-preloader/node_modules/elmx/dist/generator.js:83
  var expr = state.expr;
                  ^

TypeError: Cannot read property 'expr' of undefined
    at generate (/home/ielectric/dev/hydra-frontend/node_modules/elmx-webpack-preloader/node_modules/elmx/dist/generator.js:83:19)
    at module.exports (/home/ielectric/dev/hydra-frontend/node_modules/elmx-webpack-preloader/node_modules/elmx/dist/parser.js:38:10)
    at /home/ielectric/dev/hydra-frontend/node_modules/elmx-webpack-preloader/index.js:137:34
    at /home/ielectric/dev/hydra-frontend/node_modules/elmx-webpack-preloader/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by vic** [comment]
Hey, I just updated the [example elmx-webpack-preloader app](https://github.com/vic/elmx-webpack-boilerplate/commit/7c0c4a6442a7edbf8ec1262a56e66307d7da4b78) to Elm 0.17. 

Most important change was to [update elm-webpack-loader to 3.0.1](https://github.com/vic/elmx-webpack-boilerplate/commit/7c0c4a6442a7edbf8ec1262a56e66307d7da4b78#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R22) which actually adds support for Elm 0.17. So maybe you just need to update it on your `package.json` as well.

**Comment by vic** [comment]
I'm closing this now, no change was needed to support 0.17, just updating your package.json versions for `elm` and `elm-webpack-loader` should be enough.

**Comment by domenkozar** [comment]
I've updated to 3.0.1, but the error persists.

**Comment by vic** [comment]
Hm, could you share an small example of your `elmx` source to investigate a little further? From the stacktrace you shared, it looks like the error is produced at the `elmx` compiler, having an `undefined state`. 

As far as I could see 

``` javascript
// this is elmx-webpack-preloader/index.js at line 137
// here elmxParser is given the text content of your elmx file.
elmxParser(lines)
```

Then somehow inside of `elmx`

``` javascript
  // this is elmx/dist/parser.js line 38
  // here state.get() returns undefined !!
  return generate(state.get());
```

The only  thing I can think of is that either your file is empty, or has no html tags cause somehow the state inside elmx is not being filled. :/
