### ISSUE TITLE
Webpack 4 - Cannot read property 'elmx' of undefined

### ISSUE THREAD

**Issue by jakub-zawislak** [vic/elmx-webpack-preloader#3]
`elmx-webpack-preloader/index.js:24:35`

In webpack there is no `this.options` variable

> webpack 3 already deprecated this.options in the loader context. webpack 4 removes it now.

> Guideline: Loaders should receive all options via this.query. They should not use other ways to receive options, i. e. no property in webpack options, no environment variable.

https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

**Comment by vic** [comment]
closed by #4

**Comment by vic** [comment]
Just published `1.2.0` with webpack 4 support by @Lermex
